version: "3.3"
services:
  app:
    image: msawatzky75/discord-bot-js
    restart: always
    environment:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/db

volumes:
  data:
