version: "2"
services:
  app:
    image: msawatzky75/discord-bot-js
    restart: always
    environment:
      PREFIX: ${PREFIX}
      TOKEN: ${TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    container_name: discord_bot_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/db

volumes:
  data:

