name: Marty Nightly

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    stage: build
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t msawatzky75/marty:nightly

  push:
    runs-on: ubuntu-latest
    stage: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Push the Docker image
        run: docker push msawatzky75/marty:nightly
