name: Maria Nightly

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . -t jkoop/maria:nightly

      - name: Login to docker
        run: docker login -u jkoop -p ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Push the Docker image
        run: docker push jkoop/maria:nightly
